global:
  hosts:
    dbmigrator: "[RELEASE_NAME]-dbmigrator"
    webpublic: "[RELEASE_NAME]-webpublic"
    web: "[RELEASE_NAME]-web"
  connectionStrings:
    default: "Server=[RELEASE_NAME]-sqlserver,1433; Database=SampleTesting1; User Id=sa; Password=myPassw@rd; TrustServerCertificate=True"
  dotnetEnvironment: "Staging"
  disablePII: "false"
  stringEncryptionDefaultPassPhrase: "V1YTOivHcCn5SG6H"
  abpStudioClient:
    isLinkEnabled: "true"